<?php 
$abc =1;
switch ($abc) {
    case 'value':
        # code...
        # code...
        # code...
        # code...
        break;
    case 'value':
            # code...
            # code...
            # code...
            # code...
        break;
    case 'value':
     # code...
     # code...
     # code...
     # code...
           break;
        case 'ok':
     # code...
     # code...
     # code...
     # code...
           break;

}
?>
